name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Package Install
        run: npm ci
      - name: Run ESLint
        run: npm run eslint
      - name: Run Prettier
        run: npm run format-check
      - name: Run test
        run: npm test